### ISSUE TITLE
Source reference in Fodder gene is not allowed

### ISSUE THREAD

**Issue by fw2568** [eryph-org/dotnet-configmodel#52]
Following config is not supported:

``` yaml
# gene:cmt/starter/v100:linux
name: linux
fodder:
  - name: add-ssh-key
    source: gene:cmt/helpers/v100:linux
---
# gene:cmt/helpers/v100:linux
name: linux
fodder:
  - name: add-ssh-key
    type: ...
    content: ...
```

Therefore the source field should not be mapped in a fodder gene.

[AB#595](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/595)
