### ISSUE TITLE
Drive config should not validate size for dvd

### ISSUE THREAD

**Issue by fw2568** [eryph-org/dotnet-configmodel#65]
Currently the validation requires field size to be filled for a DVD.

``` yaml
drives:
  - name: install
    Source: S:\path.iso
    size: 1
    type: dvd
```

But size is only required for VHDs.

https://github.com/eryph-org/dotnet-configmodel/blob/2d9aab0d8079885482a535af4c52bdce2fee8b77/src/Eryph.ConfigModel.Catlets.Validation/CatletConfigValidations.cs#L34

[AB#653](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/653)
